[build]
  functions = "netlify/functions"
  publish = "public"      # Cartella fittizia (vedi sotto)
  command = "exit 0"      # Dice a Netlify: "Esci subito, non fare nulla"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200